### ISSUE TITLE
1.20.1 Port

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/starcaller#6]
ModFest 1.20 is over! So we'd happily accept a 1.20.1 port for this mod.

It's still just a toy, really, but we'll happily take port PRs and bugfixes for any major versions.

**Comment by viscountexx** [comment]
I was just coming here to look into if anyone was working on that! I'd really like to include this mod in a modpack and server for a themed event, so a backport would be amazing.
